name: peminjaman_ruang
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  file_picker: ^3.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.1
  http: ^0.13.4
  charts_flutter: ^0.12.0
  pie_chart: ^5.3.2
  google_nav_bar: ^5.0.6
  syncfusion_flutter_pdfviewer: ^20.3.59

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
